version: 2

defaults: &defaults
  docker:
  - image: circleci/golang:1.14
  working_directory: /go/src/github.com/nhood-org/nhood-engine-utils

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - vendor-cache-v0.3
    - run: make clean test build
    - save_cache:
        key: vendor-cache-v0.3
        paths:
        - "vendor"

  release:
    <<: *defaults
    steps:
    - checkout
    - run: make release-ci
    